otta:
  enabled: true
  momentum: 0.01
  update_interval_seconds: 5
head_finetune:
  enabled: true
  learning_rate: 5e-5
  batch_size: 32
  warmup_steps: 100
errp_detector:
  enabled: true
  threshold: 3.0
  refractory_seconds: 2.0
bandit:
  enabled: false
  arms: ["baseline", "aggressive", "conservative"]
  exploration: 0.1
